### PR TITLE
Prevent stale values of calculate_soil from leaking across threads

### PR DESCRIPTION
**Pull request by lrbison**
Addresses issue #135.

### CODE REVIEW

**Comment by lrbison** [comment]
Another solution would be to move calculate_soil to be local to the `noahmplsm` subroutine, but that seems like it would have farther-reaching impact.  Since all threads are on the same timestep, they should all end up with the same value of `calculate_soil`.

**Review by tslin2 — APPROVED** [review]
Thanks

**Review by RAbolafiaRosenzweig — APPROVED** [review]

**Comment by lrbison** [comment]
ping on this PR, is the testing complete?

**Comment by cenlinhe** [comment]
> ping on this PR, is the testing complete?

Sorry for the delay. Our team is overwhelmed by a number of things but this test is on top of our list and will be done soon.

**Comment by lrbison** [comment]
@cenlinhe ping on this two-line change?

**Comment by cenlinhe** [comment]
I just merged this PR change.

**Pull request merged**
