### PR TITLE
green vegetation fraction scaling of max canopy capacity of rain & snow intercept

### PR DESCRIPTION
**Pull request by tslin2**
This is a pull request method 1 of #91

### CODE REVIEW

**Comment by cenlinhe** [comment]
Let's wait until we have a discussion with Guo-Yue and Liang to see what the best strategy to fix the FVEG scaling issue would be.

**Comment by barlage** [comment]
Agreed. Note that I don't think this is the best solution to the issue. Also note that the scaling needs to occur here as well:

https://github.com/NCAR/noahmp/blob/ba9f679846d0f4e7595f219ee77474fdf70b53cb/src/CanopyHydrologyMod.F90#L70

**Comment by tslin2** [comment]
yes, agree on both!

**Comment by jesusff** [comment]
This affects the non-refactored code as well, right?
https://github.com/NCAR/noahmp/blob/release-v4.5-WRF/src/module_sf_noahmplsm.F#L1450

**Comment by barlage** [comment]
@jesusff yes, there will eventually need to be a second PR to the 4.5 branch

**Pull request closed without merging**
